//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 wtleditor.rc 使用
//
#define ID_SEPARATOR                    0
#define ID_DEFAULT_PANE                 0
#define VS_VERSION_INFO                 1
#define IDC_WTL_ROTATE_RIGHT            2
#define cmdQat                          3
#define ID_BUTTON_UNDO                  4
#define ID_BUTTON_REDO                  5
#define ID_PICOPACITY                   6
#define ID_CHAR_SPACE                   7
#define ID_LINE_SPACE                   8
#define ID_CHAR_SIZE                    9
#define IDC_CMD_HOMETAB                 100
#define IDS_APP_TITLE                   103
#define IDS_RIBBON_MARKUP               104
#define IDI_ANNOTATOR                   107
#define IDI_SMALL                       108
#define IDC_ANNOTATOR                   109
#define IDS_SAVE_FAILED_TITLE           110
#define IDD_ABOUTBOX                    111
#define IDR_VERSION                     112
#define IDR_MAINFRAME                   128
#define IDB_PNG_ARROW                   129
#define IDB_PNG_CHECKED                 130
#define IDB_PNG_UNCHECKED               131
#define IDB_PNG_BACKARROW               132
#define IDC_RIGHT                       133
#define IDC_BOTTOM                      134
#define IDC_BOTTOMRIGHT                 135
#define IDC_CENTER                      136
#define IDC_CURSOR1                     143
#define IDC_EDIT                        144
#define IDC_LEFT							145
#define IDC_CMD_VIEWTAB                 200
#define IDC_LINKGROUP                   210
#define IDC_ZOOMGROUP                   220
#define IDC_TEXTGROUP                   227
#define IDC_EDITGROUP                   230
#define IDC_FONTGROUP                   231
#define IDC_TabGroupText                232
#define IDC_TabText                     233
#define IDC_TabGroupPen                 234
#define IDC_TabPen                      235
#define IDC_TabGroupLayer               236
#define IDC_TabLayer                    237
#define HOME                            242
#define POWER                           243
#define ID_WTL_MENU_PEN                 244
#define ID_RIBBON_FONT                  245
#define sizeButton                      260
#define cropButton                      280
#define rotateButton                    290
#define rotate90Clockwise               293
#define rotate90CounterClockwise        296
#define ID_BUTTON_ZOOM_IN               300
#define ID_BUTTON_ZOOM_OUT              310
#define ID_BUTTON_ZOOM_100              320
#define ID_STANDARD_COLORPICKER         330
#define ID_WTL_MENU_TEXT                331
#define ID_WTL_STOP_TEXT                332
#define ID_WTL_MENU_COPY                333
#define ID_WTL_MENU_PASTE               335
#define ID_WTL_STOP_PEN                 336
#define ID_WTL_MENU_LAYER               337
#define ID_WTL_STOP_LAYER               338
#define ID_WTL_OPEN_LAYER_FILE          339
#define flipVertical                    340
#define flipHorizontal                  350
#define ID_FILE_MENU                    500
#define IDB_BITMAP_LINE01               501
#define IDB_BITMAP_LINE02               502
#define IDB_BITMAP_LINE03               503
#define IDB_BITMAP_LINE04               504
#define IDB_BITMAP_TOOLBAR_16           506
#define IDB_BITMAP_TOOLBAR_24           507
#define IDD_ABOUT_DIALOG                508
#define IDC_STATIC_20                   509
#define IDC_STATIC_22                   510
#define IDC_STATIC_23                   511
#define IDC_STATIC_42                   512
#define IDD_COMBBOX					513
#define ID_ANNO_FILE_OPEN               520
#define ID_ANNO_FILE_SAVE               530
#define IDR_MYPNG_SHIMMER		531
#define IDC_STATIC_33						532
#define IDC_STATIC_34						533
#define IDS_UNSUPPORTED_FILE_FORMAT_HEADER 901
#define IDS_OPEN_FILE_DIALOG_ERROR_TITLE 902
#define IDS_NO_FILES_OPENED             903
#define IDS_SOME_FILES_NOT_OPENED       904
#define IDC_STATIC_1                    1002
#define IDC_STATIC_2                    1003
#define IDC_STATIC_3                    1004
#define IDC_STATIC_4                    1005
#define IDC_STATIC_5                    1006
#define IDC_STATIC_8                    1007
#define IDC_STATIC_9                    1008
#define IDC_STATIC_10                   1009
#define IDC_RESIZE_RESET			1010
#define IDD_RESIZE_BOX				1011
#define IDDefault							1012
#define IDR_MYPNG_ABOUT					1107

#define ID_CURRENT_LEFT			1108
#define ID_CURRENT_TOP			1109
#define ID_CURRENT_WIDTH		1110
#define ID_CURRENT_HEIGHT		1111

#define IDR_MYPNG_RESIZE_LINKED		L"K:\\娱乐\\vs2022\\wtleditor\\wtleditor\\res\\resize_linked.png"
#define IDR_MYPNG_RESIZE_TITLE			L"K:\\娱乐\\vs2022\\wtleditor\\wtleditor\\res\\resize_title.jpg"
#define IDR_MYPNG_RESIZE_UNLINKED	L"K:\\娱乐\\vs2022\\wtleditor\\wtleditor\\res\\resize_unlinked.png"
#define IDR_MYPNG_RESIZE_PIC				L"K:\\娱乐\\vs2022\\wtleditor\\wtleditor\\res\\Finder.ico"
#define IDR_MYPNG_NEW_TITLE				L"K:\\娱乐\\vs2022\\wtleditor\\wtleditor\\res\\new.png"

#define ID_ANNO_FILE_SAVE_AS            5150
#define ID_ANNO_FILE_EXIT               5160
#define ATL_IDC_TAB_CONTROL             0x3020
#define ID_APPLY_NOW                    0x3021
#define ID_WIZBACK                      0x3023
#define ID_WIZNEXT                      0x3024
#define ID_WIZFINISH                    0x3025
#define IDC_SPACE                       41003
#define ATL_IDS_IDLEMESSAGE             0xE001
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_DIRECT            0xE108
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_FILE_UPDATE                  0xE10A
#define ID_FILE_SAVE_COPY_AS            0xE10B
#define ID_FILE_SEND_MAIL               0xE10C
#define ID_FILE_MRU_FIRST               0xE110
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_FILE_MRU_LAST                0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_LINK              0xE126
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_EDIT_FIND_PREVIOUS           0xE12D
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_HELP_INDEX                   0xE142
#define ID_HELP_FINDER                  0xE143
#define ID_HELP_USING                   0xE144
#define ID_CONTEXT_HELP                 0xE145
#define ID_HELP                         0xE146
#define ID_DEFAULT_HELP                 0xE147
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_PANE_CLOSE                   0xE152
#define ID_FORMAT_FONT                  0xE160
#define ID_SCROLL_UP                    0xE170
#define ID_SCROLL_DOWN                  0xE171
#define ID_SCROLL_PAGE_UP               0xE172
#define ID_SCROLL_PAGE_DOWN             0xE173
#define ID_SCROLL_TOP                   0xE174
#define ID_SCROLL_BOTTOM                0xE175
#define ID_SCROLL_LEFT                  0xE176
#define ID_SCROLL_RIGHT                 0xE177
#define ID_SCROLL_PAGE_LEFT             0xE178
#define ID_SCROLL_PAGE_RIGHT            0xE179
#define ID_SCROLL_ALL_LEFT              0xE17A
#define ID_SCROLL_ALL_RIGHT             0xE17B
#define ID_OLE_INSERT_NEW               0xE200
#define ID_OLE_EDIT_LINKS               0xE201
#define ID_OLE_EDIT_CONVERT             0xE202
#define ID_OLE_EDIT_CHANGE_ICON         0xE203
#define ID_OLE_EDIT_PROPERTIES          0xE204
#define ID_OLE_VERB_FIRST               0xE210
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801
#define ID_VIEW_REFRESH                 0xE803
#define ID_VIEW_RIBBON                  0xE804
#define ATL_IDS_SCSIZE                  0xEF00
#define ATL_IDS_SCMOVE                  0xEF01
#define ATL_IDS_SCMINIMIZE              0xEF02
#define ATL_IDS_SCMAXIMIZE              0xEF03
#define ATL_IDS_SCNEXTWINDOW            0xEF04
#define ATL_IDS_SCPREVWINDOW            0xEF05
#define ATL_IDS_SCCLOSE                 0xEF06
#define ATL_IDS_SCRESTORE               0xEF12
#define ATL_IDS_SCTASKLIST              0xEF13
#define ATL_IDS_MDICHILD                0xEF1F
#define ATL_IDS_MRU_FILE                0xEFDA
#define ID_WINDOW_TABFIRST              0xFF00
#define ID_WINDOW_TABLAST               0xFFFD
#define ID_WINDOW_SHOWTABLIST           0xFFFE

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
